"""
Saved results -> LaTeX for the report, so no number in the PDF is typed by hand.

report/tables/numbers.tex   one macro per number (\\pOneMI, \\rA, \\pA, ...)
report/tables/p2_table.tex  body rows of the Problem 2 summary table
"""

import pandas as pd
from common import RES_DIR, TAB_DIR, sci

PART_NAME = {"a": "A", "b": "B", "c": "C"}


def p_tex(log10_p: float) -> str:
    """p-value as a TeX number: plain when >= 0.001, else m x 10^e."""
    if log10_p >= -3:
        return f"{10**log10_p:.4f}"
    mant, exp = sci(log10_p)
    return f"{mant:.2f}\\times 10^{{{exp}}}"


def main() -> None:
    tab = pd.read_csv(RES_DIR / "p1_contingency.csv")
    s1 = pd.read_csv(RES_DIR / "p1_stats.csv", index_col="stat")["value"]
    p2 = pd.read_csv(RES_DIR / "p2_stats.csv")

    macros: dict[str, str] = {}
    for row in tab.itertuples():
        key = f"{row.v1}{row.v2}"
        word = {"00": "Zz", "01": "Zo", "10": "Oz", "11": "Oo"}[key]
        macros[f"nC{word}"] = f"{row.count}"
        macros[f"eC{word}"] = f"{row.expected:.2f}"
    counts = tab.set_index(["v1", "v2"])["count"]
    macros["nRowZ"] = f"{counts.loc[0].sum()}"
    macros["nRowO"] = f"{counts.loc[1].sum()}"
    macros["nColZ"] = f"{counts.xs(0, level='v2').sum()}"
    macros["nColO"] = f"{counts.xs(1, level='v2').sum()}"

    macros |= {
        "pOneN": f"{int(s1['n'])}",
        "alphaLevel": f"{s1['alpha']:.2f}",
        "pOneHx": f"{s1['H_v1_bits']:.4f}",
        "pOneHy": f"{s1['H_v2_bits']:.4f}",
        "pOneMI": f"{s1['MI_bits']:.4f}",
        "pOneMInats": f"{s1['MI_nats']:.4f}",
        "pOneNMI": f"{s1['NMI']:.4f}",
        "pOneMIp": f"{s1['MI_perm_p']:.4f}",
        "pOnePerm": f"{int(s1['MI_perm_n']):,}",
        "pOneNullMax": f"{s1['MI_null_max']:.4f}",
        "pOneJac": f"{s1['jaccard']:.4f}",
        "pOneChi": f"{s1['chi2']:.4f}",
        "pOneChiP": f"{s1['chi2_p']:.4f}",
        "pOneYates": f"{s1['chi2_yates']:.4f}",
        "pOneYatesP": f"{s1['chi2_yates_p']:.4f}",
        "pOneMinE": f"{s1['min_expected']:.2f}",
    }

    rows = []
    for r in p2.itertuples():
        k = PART_NAME[r.part]
        macros |= {
            f"n{k}": f"{r.n:,}".replace(",", "{,}"),
            f"r{k}": f"{r.r:.4f}",
            f"t{k}": f"{r.t:.2f}",
            f"df{k}": f"{r.df:,}".replace(",", "{,}"),
            f"p{k}": p_tex(r.log10_p),
            f"rho{k}": f"{r.spearman:.4f}",
            f"rabs{k}": f"{r.r_abs_x:.4f}",
            f"rej{k}": "reject" if r.reject_h0 else "do not reject",
        }
        rows.append(
            f"({r.part}) & \\texttt{{{r.file}}} & {r.n:,} & {r.r:.4f} & {r.t:.2f} & "
            f"${p_tex(r.log10_p)}$ & {'reject' if r.reject_h0 else 'do not reject'} \\\\"
        )
    macros["bSharesC"] = "yes" if bool(p2["b_gene1_is_c_prefix"].iloc[0]) else "no"

    TAB_DIR.mkdir(parents=True, exist_ok=True)
    lines = ["% Generated by hw4/code/p3_report_tables.py. Do not edit."]
    lines += [f"\\newcommand{{\\{k}}}{{{v}}}" for k, v in macros.items()]
    (TAB_DIR / "numbers.tex").write_text("\n".join(lines) + "\n")
    # A rule between every row (latex.md §8).
    (TAB_DIR / "p2_table.tex").write_text("\n\\midrule\n".join(rows) + "\n")
    print(f"{len(macros)} macros, {len(rows)} table rows -> {TAB_DIR}")


if __name__ == "__main__":
    main()
